# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json



###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8f936ee87e8e476c0af7a49b0609f2f7139f7152

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token 8f936ee87e8e476c0af7a49b0609f2f7139f7152

{
  "status": "OPEN"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/12/
Authorization: Token 0dcf1ee213c4c89d517247a344a0d0378ef53129

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
